/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appadm;
import java.awt.print.PrinterException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.ConectaBanco;
import mascaras.MascaraMesAno;
import utilitarios.InOut;

/**
 *
 * @author MC System Work's
 */
public class RelatorioMotVoucher extends javax.swing.JFrame {

    ConectaBanco con;
    ResultSet lRes =null;
    String sSql=new String();
    MascaraMesAno mascaramesano= new MascaraMesAno();
    
    

    
    public RelatorioMotVoucher() {
        super(" RELATORIO  ");
        initComponents();
     
        
      //  mesAno.setDocument(mascaramesano);
        String [] colunas = new String[]{"NumeroVoucher","Empresa","Usuario","Origem","Destino","Hora Saida","Hora Chegada","Valor Total","DataDia","DataMes","DataAno"};
        String[][] dados = new String[][]{};
        
        String [] colunas1 = new String[]{"MOTORISTA","MES","NUMERO DE VIAGENS"};
        String[][] dados1 = new String[][]{};
        String tipo = new String();
        
     
        DefaultTableModel modelo = new DefaultTableModel(dados, colunas);
        DefaultTableModel modelo2 = new DefaultTableModel(dados1, colunas1);
        tbRelatorio.setModel(modelo);
        tbRelatorio2.setModel(modelo2);
        
          
        
             
             
       
        
       
       // carregaDados();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Pesquisa = new javax.swing.JButton();
        DataMes = new javax.swing.JComboBox();
        ClientePesquisa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRelatorio = new javax.swing.JTable();
        Ano1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRelatorio2 = new javax.swing.JTable();
        Imprimir1 = new javax.swing.JButton();
        Pesquisa1 = new javax.swing.JButton();
        DataMes1 = new javax.swing.JComboBox();
        Ano2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 52, 75));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo4.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Relatório");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-fechar2.png"))); // NOI18N
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(44, 52, 75));

        Pesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_pesquisar.gif"))); // NOI18N
        Pesquisa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PesquisaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PesquisaMousePressed(evt);
            }
        });

        DataMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JANEIRO", "FEVEREIRO", "MARCO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO" }));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CLIENTE :");

        Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_impressora.gif"))); // NOI18N
        Imprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Imprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ImprimirMousePressed(evt);
            }
        });

        tbRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbRelatorio);

        Ano1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099", "2100" }));
        Ano1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClientePesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DataMes, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ano1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(Imprimir)
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Imprimir)
                            .addComponent(ClientePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pesquisa)
                            .addComponent(DataMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ano1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31))))
        );

        jTabbedPane1.addTab("VOUCHER", jPanel2);

        jPanel3.setBackground(new java.awt.Color(44, 52, 75));

        tbRelatorio2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbRelatorio2);

        Imprimir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_impressora.gif"))); // NOI18N
        Imprimir1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Imprimir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Imprimir1MousePressed(evt);
            }
        });

        Pesquisa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_pesquisar.gif"))); // NOI18N
        Pesquisa1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pesquisa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pesquisa1MousePressed(evt);
            }
        });
        Pesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pesquisa1ActionPerformed(evt);
            }
        });

        DataMes1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JANEIRO", "FEVEREIRO", "MARCO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO" }));

        Ano2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099", "2100" }));
        Ano2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(DataMes1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ano2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(483, 483, 483)
                            .addComponent(Pesquisa1)
                            .addGap(18, 18, 18)
                            .addComponent(Imprimir1)
                            .addGap(8, 8, 8)))
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ano2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(Imprimir1)
                        .addComponent(Pesquisa1))
                    .addGap(11, 11, 11)))
        );

        jTabbedPane1.addTab("MOTORISTAS", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(158, 158, 158)
                        .addComponent(jLabel2))
                    .addComponent(jButton2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    public void populaTabela(ResultSet res) {
           DefaultTableModel modelo1 = (DefaultTableModel) tbRelatorio.getModel();
       
        try {
        con=new ConectaBanco();
        
        String sSql = "select NUMEROVOUCHER,EMPRESA,USUARIO,ORIGEM,DESTINO,HSAIDA,HCHEGADA,VALORTOTAL,DATADIA,DATAMES,DATAANO from Voucher where empresa ='"+ClientePesquisa.getText()+"'AND DATAMES='"+DataMes.getSelectedItem()+"'and dataano = '"+Ano1.getSelectedItem()+"';";
        con.conecta();
         if(!con.conecta())
        {
            InOut.MsgDeErro("AppAdm","Erro ao conectar");
            return;            
        }
        con.executaSelect(sSql);
       
        System.out.println(sSql);
        lRes = con.resultset;      
        System.out.println(lRes);
            modelo1.setRowCount(0);
            while (lRes.next()) {
                modelo1.addRow(new Object[]{
                            lRes.getString("NUMEROVOUCHER"),
                            lRes.getString("EMPRESA"),
                            lRes.getString("USUARIO"),
                            lRes.getString("ORIGEM"),
                            lRes.getString("DESTINO"),
                            lRes.getString("HSAIDA"),
                            lRes.getString("HCHEGADA"),
                            lRes.getString("VALORTOTAL"),
                            lRes.getString("DATADIA"),
                            lRes.getString("DATAMES"),
                            lRes.getString("DATAANO"),
                            
                            
                            
                            
                            
                            
                            
                            });

            }
            tbRelatorio.setModel(modelo1);
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(ClientePesquisa, ex);
        }
        con.desconecta();
    }
    
  
    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
       // InicialTela abrir=new InicialTela();
        //abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MousePressed

    private void PesquisaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesquisaMousePressed

 
        con=new ConectaBanco();
        con.conecta();
        sSql = "select NUMEROVOUCHER,EMPRESA,USUARIO,ORIGEM,DESTINO,HSAIDA,HCHEGADA,VALORTOTAL,DATADIA,DATAMES,DATAANO from Voucher where empresa ='"+ClientePesquisa.getText()+"'AND DATAMES='"+DataMes.getSelectedItem()+"'and dataano = '"+Ano1.getSelectedItem()+"'and status='ativo';";
           con.executaSelect(sSql);
          
           populaTabela(con.resultset);   
           System.out.println(sSql);
       
        con.desconecta();
        
    }//GEN-LAST:event_PesquisaMousePressed

    private void ImprimirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImprimirMousePressed
        try {
            // TODO add your handling code here:
            tbRelatorio.print();
        } catch (PrinterException ex) {
            Logger.getLogger(RelatorioMotVoucher.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ImprimirMousePressed

private void Imprimir1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imprimir1MousePressed
        try {
            // TODO add your handling code here:
                InOut.MsgDeErro("ERRO NA IMPRESSÃO", sSql);
                tbRelatorio2.print();
        } catch (PrinterException ex) {
            InOut.MsgDeErro("ERRO NA IMPRESSÃO", sSql);
        }
    
    
    
    
}//GEN-LAST:event_Imprimir1MousePressed

private void Pesquisa1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesquisa1MousePressed
        con=new ConectaBanco();
        con.conecta();
        sSql = "SELECT MOTORISTA,DATAMES,dataano,COUNT(*) AS VIAGENS FROM VOUCHER where datames='"+DataMes1.getSelectedItem()+"'AND DATAANO='"+Ano2.getSelectedItem()+"'group by motorista;";
           con.executaSelect(sSql);
           System.out.println(sSql);
           populaTabela1(con.resultset);
        con.desconecta();





}//GEN-LAST:event_Pesquisa1MousePressed

private void PesquisaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesquisaMouseExited
// TODO add your handling code here:
}//GEN-LAST:event_PesquisaMouseExited

    private void Pesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pesquisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pesquisa1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioMotVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioMotVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioMotVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioMotVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RelatorioMotVoucher().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Ano1;
    private javax.swing.JComboBox Ano2;
    private javax.swing.JTextField ClientePesquisa;
    private javax.swing.JComboBox DataMes;
    private javax.swing.JComboBox DataMes1;
    private javax.swing.JButton Imprimir;
    private javax.swing.JButton Imprimir1;
    private javax.swing.JButton Pesquisa;
    private javax.swing.JButton Pesquisa1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbRelatorio;
    private javax.swing.JTable tbRelatorio2;
    // End of variables declaration//GEN-END:variables

    public void populaTabela1(ResultSet res) {
        
            DefaultTableModel modelo1 = (DefaultTableModel) tbRelatorio2.getModel();
       
        try {
        con=new ConectaBanco();
        
        sSql = "SELECT MOTORISTA,DATAMES,dataano,COUNT(*) AS VIAGENS FROM VOUCHER where datames='"+DataMes1.getSelectedItem()+"'AND DATAANO='"+Ano2.getSelectedItem()+"'group by motorista;";

        con.conecta();
         if(!con.conecta())
        {
            InOut.MsgDeErro("AppAdm","Erro ao conectar");
            return;            
        }
        con.executaSelect(sSql);
       
        System.out.println(sSql);
        lRes = con.resultset;      
        System.out.println(lRes);
            modelo1.setRowCount(0);
            while (lRes.next()) {
                modelo1.addRow(new Object[]{
                            lRes.getString("MOTORISTA"),
                            lRes.getString("DATAMES"),
                            lRes.getString("VIAGENS")});

            }
            tbRelatorio2.setModel(modelo1);
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(ClientePesquisa, ex);
        }
        con.desconecta();
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}
