package appadm;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import utilitarios.ConectaBanco;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import utilitarios.InOut;
import mascaras.*;



/**
 *
 * @author MC System Work's
 */
public class Cadastro extends javax.swing.JFrame {
    ConectaBanco con;
    MascaraCNPJ mascnumero1=new MascaraCNPJ();
    MascaraNumero mascnumero2=new MascaraNumero();
    MascaraCEP mascnumero3=new MascaraCEP();
    MascaraValor mascvalor=new MascaraValor();
    MascaraCPF masccpf=new MascaraCPF();
    MascaraRG mascrg=new MascaraRG();
    MascaraCNH masccnh=new MascaraCNH();
    MascaraNumero mascnumero4=new MascaraNumero();
    MascaraCEP masccep=new MascaraCEP();
     ResultSet lRes =null;
      String sCliente = new String();
      String sMotorista = new String();
      
     int lIdCadEmpresa=0;
     int lIdCadMotorista=0;
    
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        super(" Cadastro");
        
        
        
       // this.setUndecorated(true);
        initComponents();
        
        EmpresaCNPJ.setDocument(mascnumero1);
        EmpresaNum.setDocument(mascnumero2);
        EmpresaCEP.setDocument(mascnumero3);
        RodKM.setDocument(mascvalor);
        MotCPF.setDocument(masccpf);
        MotRG.setDocument(mascrg);
        MotCNH.setDocument(masccnh);
        MotNum.setDocument(mascnumero4);
        MotCEP.setDocument(masccep);
        
        String[] colunas1 = new String[]{"EMPRESA","CNPJ","INSCRIÇÃO ESTADUAL"};
        String[] colunas2 = new String[]{"MOTORISTA","CNH","CARRO","STATUS"};
        String[][] dados1 = new String[][]{};
        String[][] dados2 = new String[][]{};
        DefaultTableModel modelo1= new DefaultTableModel(dados1, colunas1);
        DefaultTableModel modelo2= new DefaultTableModel(dados2, colunas2);
        TabEmpresa.setModel(modelo1);
        TabMotorista.setModel(modelo2);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        SalvaCliente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EmpresaNome = new javax.swing.JTextField();
        EmpresaCNPJ = new javax.swing.JTextField();
        EmpresaRS = new javax.swing.JTextField();
        EmpresaIE = new javax.swing.JTextField();
        EmpresaEnd = new javax.swing.JTextField();
        EmpresaNum = new javax.swing.JTextField();
        EmpresaBairro = new javax.swing.JTextField();
        EmpresaCidade = new javax.swing.JTextField();
        EmpresaEstado = new javax.swing.JTextField();
        EmpresaCEP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        RodKM = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TelEmpresa = new javax.swing.JTextField();
        liberaUsu = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabEmpresa = new javax.swing.JTable();
        PesquisaEmpresa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        MotNome = new javax.swing.JTextField();
        MotCPF = new javax.swing.JTextField();
        MotRG = new javax.swing.JTextField();
        MotCNH = new javax.swing.JTextField();
        MotBairro = new javax.swing.JTextField();
        MotNum = new javax.swing.JTextField();
        MotEndereco = new javax.swing.JTextField();
        MotComplemento = new javax.swing.JTextField();
        MotCidade = new javax.swing.JTextField();
        MotEstado = new javax.swing.JTextField();
        MotCEP = new javax.swing.JTextField();
        SalvaMotorista = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Telefone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TelCelular = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ModCarro = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        MarcaCarro = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        PlacaCarro = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabMotorista = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PesquisaMotorista = new javax.swing.JTextField();
        Ativo = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 52, 75));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo4.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CADASTRO");

        jTabbedPane5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(44, 52, 75));

        SalvaCliente.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        SalvaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        SalvaCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SalvaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SalvaClienteMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ESTADO :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CIDADE :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ENDEREÇO :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BAIRRO :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NUMERO :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INSCRIÇÃO ESTADUAL :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CNPJ :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CEP :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMPRESA :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RAZÃO SOCIAL :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("VALOR POR KM RODADO :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TELEFONE:");

        liberaUsu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "LIBERADO", "NÃO LIBERADO", " " }));

        TabEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabEmpresaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabEmpresa);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_pesquisar.gif"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_atualizar.jpg"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmpresaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmpresaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmpresaCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RodKM, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(liberaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EmpresaEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EmpresaNum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EmpresaBairro))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(EmpresaRS))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(EmpresaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(EmpresaCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(EmpresaIE, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PesquisaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SalvaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {SalvaCliente, jButton1});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(EmpresaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(EmpresaCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(EmpresaRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpresaIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(EmpresaEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpresaNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpresaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(EmpresaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpresaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpresaCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(RodKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(TelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liberaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                    .addComponent(SalvaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(PesquisaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SalvaCliente, jButton1, jButton2});

        jTabbedPane5.addTab("EMPRESA", jPanel2);

        jPanel3.setBackground(new java.awt.Color(44, 52, 75));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ENDEREÇO :");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CNH :");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("BAIRRO :");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("NUMERO :");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("RG :");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ESTADO :");

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("NOME :");

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("CPF :");

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("CEP :");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("COMPLEMENTO :");

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("CIDADE :");

        SalvaMotorista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        SalvaMotorista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SalvaMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SalvaMotoristaMousePressed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TEL 1 :");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CELULAR :");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MODELO CARRO :");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("MARCA CARRO :");

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("PLACA CARRO :");

        TabMotorista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabMotoristaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabMotorista);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_atualizar.jpg"))); // NOI18N
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_pesquisar.gif"))); // NOI18N
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });

        Ativo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "INATIVO" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ModCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MotCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Ativo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MotNome))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MotCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MotRG, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MotCNH))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MotEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MotNum, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MotBairro))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MotComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MotCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MotEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(PesquisaMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(SalvaMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(MotNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel22)
                    .addComponent(jLabel19)
                    .addComponent(MotCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MotRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MotCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(MotBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MotNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MotEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(MotComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jLabel23)
                        .addComponent(MotCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MotEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(MotCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(TelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ModCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(MarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(PlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PesquisaMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(SalvaMotorista)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SalvaMotorista, jButton3, jButton4});

        jTabbedPane5.addTab("MOTORISTA", jPanel3);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-fechar2.png"))); // NOI18N
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(192, 192, 192)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(609, 609, 609)
                        .addComponent(jButton7))
                    .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        // TODO add your handling code here:
        //InicialTela abrir=new InicialTela();
       // abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7MousePressed

private void SalvaMotoristaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvaMotoristaMousePressed
        // TODO add your handling code here:
        String sSql=new String();
        con=new ConectaBanco();
        sSql="INSERT INTO CADMOTORISTA (NOME,CPF,RG,CNH,ENDERECO,NUMEND,COMPL,BAIRRO,CIDADE,ESTADO,CEP,TELEFONE,TELCELULAR,ATIVO,MODELOCARRO,MARCACARRO,PLACACARRO) "
                + "VALUES('"
                +MotNome.getText()+"','"+MotCPF.getText()+"','"+MotRG.getText()+
                "','"+MotCNH.getText()+"','"+MotEndereco.getText()+"','"
                +MotNum.getText()+"','"+MotComplemento.getText()+"','"+MotBairro.getText()
                +"','"+MotCidade.getText()+"','"+MotEstado.getText()+"','"+MotCEP.getText()+"','"+
                Telefone.getText()+"','"+TelCelular.getText()+"','"+Ativo.getSelectedItem()+"','"+ModCarro.getText()+"','"+
                MarcaCarro.getText()+"','"+PlacaCarro.getText()+"');";
        if(!con.conecta())
        {
            InOut.MsgDeErro("AppAdm","Erro ao conectar");
            return;            
        }
        con.conecta();
        con.executa(sSql);
        System.out.println(sSql);
        con.desconecta();
        //InOut.MsgDeInformacao(null, "INFORMAÇÕES SALVAS COM SUCESSO");
        this.LimpaCampos1();
}//GEN-LAST:event_SalvaMotoristaMousePressed

private void SalvaClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvaClienteMousePressed
        // TODO add your handling code here:
        String sSql=new String();
        con=new ConectaBanco();
        sSql="INSERT INTO CADEMPRESA (NOMEEMPRESA,CNPJ,RAZAOSOCIAL,INSESTADUAL,RUA,NUMERO,BAIRRO,CIDADE,ESTADO,CEP,VALORPORKM,TELEFONEEMPRESA,LIBERADO)"
                + " VALUES ('"+EmpresaNome.getText()+"','"+EmpresaCNPJ.getText()+"','"+EmpresaRS.getText()+"','"+EmpresaIE.getText()+"','"+EmpresaEnd.getText()+"','"+EmpresaNum.getText()+"','"+EmpresaBairro.getText()+"','"+EmpresaCidade.getText()+"','"+EmpresaEstado.getText()+"','"+EmpresaCEP.getText()+"','"+RodKM.getText()+"','"+TelEmpresa.getText()+"','"+liberaUsu.getSelectedItem()+"')";
       if(!con.conecta())
        {
            InOut.MsgDeErro("AppAdm","Erro ao conectar");
            return;            
        }
        con.conecta();
        con.executa(sSql);
       // System.out.println(sSql);
        con.desconecta();
       // InOut.MsgDeInformacao(null, "INFORMAÇÕES SALVAS COM SUCESSO");
        this.LimpaCampos();     
}//GEN-LAST:event_SalvaClienteMousePressed

private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
con=new ConectaBanco();
        String sSql=new String();
        sSql="Select NOMEEMPRESA,CNPJ,INSESTADUAL from cadempresa where nomeempresa='"+PesquisaEmpresa.getText()+"';";
       
        con.conecta();
        con.executaSelect(sSql);
        System.out.println(sSql);
        populaTabela1(con.resultset);
        con.desconecta();
    
    
    
    
}//GEN-LAST:event_jButton1MousePressed

private void TabEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabEmpresaMouseClicked
// TODO add your handling code here:
   // SalvaCliente.setVisible(false);
    jButton2.setVisible(true);
    
    int linha=0;
    linha=TabEmpresa.getSelectedRow();
    //Empresa1.setText(TabPesqCliente.getValueAt(linha, coluna).toString());
    
    sCliente = TabEmpresa.getValueAt(linha, 0).toString();
    
    
       con=new ConectaBanco();
        String sSql=new String();
        sSql="Select * from cadempresa where nomeempresa='"+sCliente+"';";
        con.conecta();
         if(!con.conecta())
        {
            InOut.MsgDeErro("AppAdm","Erro ao conectar");
            return;            
        }
        con.executaSelect(sSql);
        
        lRes=con.resultset;        
        
        try 
        {           
            while (lRes.next())
            {
                 //r =Integer.parseInt(lRes.getString("IdVoucher"));
                // Number.setText(lRes.getString("NumeroVoucher"));
                lIdCadEmpresa =Integer.parseInt(lRes.getString("IDCADEMPRESA"));
                 EmpresaNome.setText(lRes.getString("NOMEEMPRESA"));
                 EmpresaCNPJ.setText(lRes.getString("CNPJ"));
                 EmpresaRS.setText(lRes.getString("RAZAOSOCIAL"));
                 EmpresaIE.setText(lRes.getString("INSESTADUAL"));
                 EmpresaEnd.setText(lRes.getString("RUA"));
                 EmpresaNum.setText(lRes.getString("NUMERO"));
                 EmpresaBairro.setText(lRes.getString("BAIRRO"));
                 EmpresaCidade.setText(lRes.getString("CIDADE"));
                 EmpresaEstado.setText(lRes.getString("ESTADO"));
                 EmpresaCEP.setText(lRes.getString("CEP"));
                 RodKM.setText(lRes.getString("VALORPORKM"));
                 TelEmpresa.setText(lRes.getString("TELEFONEEMPRESA"));
                 liberaUsu.setSelectedItem(lRes.getString("LIBERADO"));
                                               
            }            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(ExecutiveService.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        con.desconecta();
}//GEN-LAST:event_TabEmpresaMouseClicked

private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
// TODO add your handling code here:
     con=new ConectaBanco();
        String sSql=new String();
        sSql="Update cadempresa set liberado='"+liberaUsu.getSelectedItem()+"' where IDCADEMPRESA = "+lIdCadEmpresa+";";
        con.conecta();
         if(!con.conecta())
        {
            InOut.MsgDeErro("AppAdm","Erro ao conectar");
            return;            
        }
        System.out.println(sSql);
        con.executa(sSql);
        con.desconecta();
        InOut.MsgDeInformacao(null,"INFORMAÇÕES ATUALIZADAS COM SUCESSO!!!" );
        this.LimpaCampos();
        populaTabela1(con.resultset);
    
         SalvaCliente.setVisible(false);
        jButton2.setVisible(false);
    
    
    
    
    
    
    
    
}//GEN-LAST:event_jButton2MousePressed

private void TabMotoristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabMotoristaMouseClicked
int linha=0;
    linha=TabMotorista.getSelectedRow();
    //Empresa1.setText(TabPesqCliente.getValueAt(linha, coluna).toString());
    
    sMotorista = TabMotorista.getValueAt(linha, 0).toString();
    
    
       con=new ConectaBanco();
        String sSql=new String();
        sSql="Select * from CADMOTORISTA where NOME='"+sMotorista+"';";
        con.conecta();
         if(!con.conecta())
        {
            InOut.MsgDeErro("AppAdm","Erro ao conectar");
            return;            
        }
        con.executaSelect(sSql);
        
        lRes=con.resultset;        
        
        try 
        {           
            while (lRes.next())
            {
                 //r =Integer.parseInt(lRes.getString("IdVoucher"));
                // Number.setText(lRes.getString("NumeroVoucher"));
                lIdCadMotorista =Integer.parseInt(lRes.getString("IDCADMOTORISTA"));
                 MotNome.setText(lRes.getString("NOME"));
                 MotCPF.setText(lRes.getString("cpf"));
                 MotRG.setText(lRes.getString("rg"));
                 MotCNH.setText(lRes.getString("cnh"));
                 MotEndereco.setText(lRes.getString("endereco"));
                 MotNum.setText(lRes.getString("numend"));
                 MotComplemento.setText(lRes.getString("compl"));
                 MotBairro.setText(lRes.getString("bairro"));
                 MotCidade.setText(lRes.getString("cidade"));
                 MotEstado.setText(lRes.getString("estado"));
                 MotCEP.setText(lRes.getString("cep"));
                 ModCarro.setText(lRes.getString("modelocarro"));
                 MarcaCarro.setText(lRes.getString("marcacarro"));
                 PlacaCarro.setText(lRes.getString("placacarro"));
                 Ativo.setSelectedItem(lRes.getString("INSESTADUAL"));
                 Telefone.setText(lRes.getString("telefone"));
                 TelCelular.setText(lRes.getString("telcelular"));
                 
                 
                 
                 
            }            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(ExecutiveService.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        con.desconecta();
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}//GEN-LAST:event_TabMotoristaMouseClicked

private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
// TODO add your handling code here:
    
    con=new ConectaBanco();
        String sSql=new String();
        sSql="Update cadmotorista set ativo='"+Ativo.getSelectedItem()+"',endereco='"+MotEndereco.getText()+"',numend='"+MotNum.getText()+"',compl='"+MotComplemento.getText()+"'"
                + ",bairro='"+MotBairro.getText()+"'"
                + ",cidade='"+MotCidade.getText()+"'"
                + ",estado='"+MotEstado.getText()+"'"
                + ",cep='"+MotCEP.getText()+"'"
                + ",modelocarro='"+ModCarro.getText()+"'"
                + ",marcacarro='"+MarcaCarro.getText()+"'"
                + ",placacarro='"+PlacaCarro.getText()+"'"
                + ",telefone='"+Telefone.getText()+"'"
                + ",telcelular='"+TelCelular.getText()+"'"
                
                
                + " where IDCADmotorista = "+lIdCadMotorista+";";
        con.conecta();
         if(!con.conecta())
        {
            InOut.MsgDeErro("AppAdm","Erro ao conectar");
            return;            
        }
        System.out.println(sSql);
        con.executa(sSql);
        con.desconecta();
        InOut.MsgDeInformacao(null,"INFORMAÇÕES ATUALIZADAS COM SUCESSO!!!" );
        this.LimpaCampos();
        populaTabela2(con.resultset);
    
         
       // jButton2.setVisible(false);
    
    
    
}//GEN-LAST:event_jButton3MousePressed

private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed

    con=new ConectaBanco();
        String sSql=new String();
         sSql="Select nome,cnh,modelocarro,ativo from cadmotorista where nome='"+PesquisaMotorista.getText()+"';";
        con.conecta();
        con.executaSelect(sSql);
        System.out.println(sSql);
        populaTabela2(con.resultset);
        con.desconecta();
    

    
}//GEN-LAST:event_jButton4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        try {
            // TODO code application logic here
      
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppAdm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AppAdm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AppAdm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AppAdm.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Ativo;
    private javax.swing.JTextField EmpresaBairro;
    private javax.swing.JTextField EmpresaCEP;
    private javax.swing.JTextField EmpresaCNPJ;
    private javax.swing.JTextField EmpresaCidade;
    private javax.swing.JTextField EmpresaEnd;
    private javax.swing.JTextField EmpresaEstado;
    private javax.swing.JTextField EmpresaIE;
    private javax.swing.JTextField EmpresaNome;
    private javax.swing.JTextField EmpresaNum;
    private javax.swing.JTextField EmpresaRS;
    private javax.swing.JTextField MarcaCarro;
    private javax.swing.JTextField ModCarro;
    private javax.swing.JTextField MotBairro;
    private javax.swing.JTextField MotCEP;
    private javax.swing.JTextField MotCNH;
    private javax.swing.JTextField MotCPF;
    private javax.swing.JTextField MotCidade;
    private javax.swing.JTextField MotComplemento;
    private javax.swing.JTextField MotEndereco;
    private javax.swing.JTextField MotEstado;
    private javax.swing.JTextField MotNome;
    private javax.swing.JTextField MotNum;
    private javax.swing.JTextField MotRG;
    private javax.swing.JTextField PesquisaEmpresa;
    private javax.swing.JTextField PesquisaMotorista;
    private javax.swing.JTextField PlacaCarro;
    private javax.swing.JTextField RodKM;
    private javax.swing.JButton SalvaCliente;
    private javax.swing.JButton SalvaMotorista;
    private javax.swing.JTable TabEmpresa;
    private javax.swing.JTable TabMotorista;
    private javax.swing.JTextField TelCelular;
    private javax.swing.JTextField TelEmpresa;
    private javax.swing.JTextField Telefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JComboBox liberaUsu;
    // End of variables declaration//GEN-END:variables

    private void LimpaCampos() {
        
        EmpresaBairro.setText("");
        EmpresaCEP.setText("");
        EmpresaCNPJ.setText("");
        EmpresaCidade.setText("");
        EmpresaEnd.setText("");
        EmpresaEstado.setText("");
        EmpresaIE.setText("");
        EmpresaNome.setText("");
        EmpresaNum.setText("");
        EmpresaRS.setText("");
        RodKM.setText("");
    }

    private void LimpaCampos1() {
        
     MotBairro.setText("");
     MotCEP.setText("");
     MotCNH.setText("");
     MotCPF.setText("");
     MotCidade.setText("");
     MotComplemento.setText("");
     MotEndereco.setText("");
     MotEstado.setText("");
     MotNome.setText("");
     MotNum.setText("");
     MotRG.setText("");
                
    }
    
    public void populaTabela1(ResultSet res) {
        DefaultTableModel modelo1 = (DefaultTableModel) TabEmpresa.getModel();
       
        try {
        con=new ConectaBanco();
       //"EMPRESA","CNPJ","INSCRIÇÃO ESTADUAL"};
        String sSql = "select NOMEEMPRESA,CNPJ,INSESTADUAL"
                + " from CADEMPRESA where NOMEempresa ='"
                +PesquisaEmpresa.getText()+"';";
        con.conecta();
         if(!con.conecta())
        {
            InOut.MsgDeErro("AppAdm","Erro ao conectar");
            return;            
        }
        con.executaSelect(sSql);
       
        System.out.println(sSql);
        lRes = con.resultset;      
        System.out.println(lRes);
            modelo1.setRowCount(0);
            while (lRes.next()) {
                modelo1.addRow(new Object[]{
                            lRes.getString("NOMEEMPRESA"),
                            lRes.getString("CNPJ"),
                            lRes.getString("INSESTADUAL"),
                            
                            
        
                            
                            });

            }
            TabEmpresa.setModel(modelo1);
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(PesquisaEmpresa, ex);
        }
        con.desconecta();
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    private void populaTabela2(ResultSet res) {
            DefaultTableModel modelo1 = (DefaultTableModel) TabMotorista.getModel();
       
        try {
        con=new ConectaBanco();
        
        String sSql = "select NOME,CNH,MODELOCARRO,ATIVO"
                + " from CADMOTORISTA where NOME ='"
                +PesquisaMotorista.getText()+"';";
        con.conecta();
         if(!con.conecta())
        {
            InOut.MsgDeErro("AppAdm","Erro ao conectar");
            return;            
        }
        con.executaSelect(sSql);
       
        System.out.println(sSql);
        lRes = con.resultset;      
        System.out.println(lRes);
            modelo1.setRowCount(0);
            while (lRes.next()) {
                modelo1.addRow(new Object[]{
                            lRes.getString("NOME"),
                            lRes.getString("CNH"),
                            lRes.getString("MODELOCARRO"),
                            lRes.getString("ATIVO"),
                            
        
                            
                            });

            }
            TabMotorista.setModel(modelo1);
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(PesquisaMotorista, ex);
        }
        con.desconecta();
    }
        
        
        
        
        
        
    }
    
    
    
    
    
    
    
    

